"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GENERIC_EVENT = exports.EVENTS_BY_CHARACTER = exports.EVENTS = exports.CHARACTER_NAME_MAP = exports.CHARACTERS = void 0;
var characters_1 = require("./characters");
Object.defineProperty(exports, "CHARACTERS", { enumerable: true, get: function () { return characters_1.CHARACTERS; } });
Object.defineProperty(exports, "CHARACTER_NAME_MAP", { enumerable: true, get: function () { return characters_1.CHARACTER_NAME_MAP; } });
var events_1 = require("./events");
Object.defineProperty(exports, "EVENTS", { enumerable: true, get: function () { return events_1.EVENTS; } });
Object.defineProperty(exports, "EVENTS_BY_CHARACTER", { enumerable: true, get: function () { return events_1.EVENTS_BY_CHARACTER; } });
Object.defineProperty(exports, "GENERIC_EVENT", { enumerable: true, get: function () { return events_1.GENERIC_EVENT; } });
