"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CHARACTER_WEIGHT_RULES = exports.FAILURE_RULES = exports.STATUS_RULES = exports.ACTION_HAZARD_MAP = exports.EVENT_HAZARD_MAP = exports.buildOptions = exports.ACTION_OPTION_POLICY = exports.ACTION_DISPLAY = exports.ACTION_MODIFIERS = exports.ACTION_RULES = exports.timePeriodWeightModifiers = exports.timePeriodForTurn = exports.TIME_PERIOD_RULES = exports.tierByRoll = exports.resolutionTierForScore = exports.RESOLUTION_TIER_RULES = exports.defaultProject = exports.DEFAULT_PROJECT = exports.TURNS_PER_DAY = exports.RESOURCE_DEFINITIONS = exports.INITIAL_STATE = exports.RESOURCE_ORDER = void 0;
var resources_1 = require("./resources");
Object.defineProperty(exports, "RESOURCE_ORDER", { enumerable: true, get: function () { return resources_1.RESOURCE_ORDER; } });
Object.defineProperty(exports, "INITIAL_STATE", { enumerable: true, get: function () { return resources_1.INITIAL_STATE; } });
Object.defineProperty(exports, "RESOURCE_DEFINITIONS", { enumerable: true, get: function () { return resources_1.RESOURCE_DEFINITIONS; } });
Object.defineProperty(exports, "TURNS_PER_DAY", { enumerable: true, get: function () { return resources_1.TURNS_PER_DAY; } });
Object.defineProperty(exports, "DEFAULT_PROJECT", { enumerable: true, get: function () { return resources_1.DEFAULT_PROJECT; } });
Object.defineProperty(exports, "defaultProject", { enumerable: true, get: function () { return resources_1.defaultProject; } });
var resolution_1 = require("./resolution");
Object.defineProperty(exports, "RESOLUTION_TIER_RULES", { enumerable: true, get: function () { return resolution_1.RESOLUTION_TIER_RULES; } });
Object.defineProperty(exports, "resolutionTierForScore", { enumerable: true, get: function () { return resolution_1.resolutionTierForScore; } });
Object.defineProperty(exports, "tierByRoll", { enumerable: true, get: function () { return resolution_1.tierByRoll; } });
var time_period_1 = require("./time-period");
Object.defineProperty(exports, "TIME_PERIOD_RULES", { enumerable: true, get: function () { return time_period_1.TIME_PERIOD_RULES; } });
Object.defineProperty(exports, "timePeriodForTurn", { enumerable: true, get: function () { return time_period_1.timePeriodForTurn; } });
Object.defineProperty(exports, "timePeriodWeightModifiers", { enumerable: true, get: function () { return time_period_1.timePeriodWeightModifiers; } });
var actions_1 = require("./actions");
Object.defineProperty(exports, "ACTION_RULES", { enumerable: true, get: function () { return actions_1.ACTION_RULES; } });
Object.defineProperty(exports, "ACTION_MODIFIERS", { enumerable: true, get: function () { return actions_1.ACTION_MODIFIERS; } });
Object.defineProperty(exports, "ACTION_DISPLAY", { enumerable: true, get: function () { return actions_1.ACTION_DISPLAY; } });
Object.defineProperty(exports, "ACTION_OPTION_POLICY", { enumerable: true, get: function () { return actions_1.ACTION_OPTION_POLICY; } });
Object.defineProperty(exports, "buildOptions", { enumerable: true, get: function () { return actions_1.buildOptions; } });
var hazards_1 = require("./hazards");
Object.defineProperty(exports, "EVENT_HAZARD_MAP", { enumerable: true, get: function () { return hazards_1.EVENT_HAZARD_MAP; } });
Object.defineProperty(exports, "ACTION_HAZARD_MAP", { enumerable: true, get: function () { return hazards_1.ACTION_HAZARD_MAP; } });
Object.defineProperty(exports, "STATUS_RULES", { enumerable: true, get: function () { return hazards_1.STATUS_RULES; } });
Object.defineProperty(exports, "FAILURE_RULES", { enumerable: true, get: function () { return hazards_1.FAILURE_RULES; } });
Object.defineProperty(exports, "CHARACTER_WEIGHT_RULES", { enumerable: true, get: function () { return hazards_1.CHARACTER_WEIGHT_RULES; } });
